In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification


In [21]:
X, y = make_classification(n_samples=1000, n_features=10,n_classes=2,random_state=15)

In [ ]:
print("e")

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [24]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression('l2')
model.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [25]:
y_pred = model.predict(X_test)
print("Predictions:", y_pred)

Predictions: [0 0 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1
 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1
 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0]


In [26]:
model.predict_proba(X_test)

array([[9.42226999e-01, 5.77730015e-02],
       [6.95711754e-01, 3.04288246e-01],
       [8.60254154e-01, 1.39745846e-01],
       [1.05812490e-01, 8.94187510e-01],
       [2.37973857e-01, 7.62026143e-01],
       [5.79148690e-01, 4.20851310e-01],
       [8.22406717e-01, 1.77593283e-01],
       [2.16522415e-04, 9.99783478e-01],
       [1.27516476e-02, 9.87248352e-01],
       [3.33575526e-03, 9.96664245e-01],
       [7.72851220e-03, 9.92271488e-01],
       [5.69790313e-01, 4.30209687e-01],
       [6.79555293e-02, 9.32044471e-01],
       [9.76154600e-01, 2.38454005e-02],
       [1.26165568e-02, 9.87383443e-01],
       [8.54363082e-01, 1.45636918e-01],
       [9.95333336e-01, 4.66666442e-03],
       [1.71297433e-02, 9.82870257e-01],
       [9.76335169e-01, 2.36648314e-02],
       [4.30744228e-02, 9.56925577e-01],
       [3.42350625e-02, 9.65764938e-01],
       [3.62843197e-02, 9.63715680e-01],
       [5.77767187e-02, 9.42223281e-01],
       [8.20533709e-01, 1.79466291e-01],
       [8.519094

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [28]:
score = accuracy_score(y_test, y_pred)  
print("Accuracy:", score)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

Accuracy: 0.93
Confusion Matrix:
 [[96  5]
 [ 9 90]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93       101
           1       0.95      0.91      0.93        99

    accuracy                           0.93       200
   macro avg       0.93      0.93      0.93       200
weighted avg       0.93      0.93      0.93       200



In [29]:
model_1 = LogisticRegression()
penalty = ['l1', 'l2', 'elasticnet']
c_values = [0.01, 0.1, 1, 10, 100]
solver = ['liblinear', 'saga','lbfgs', 'newton-cg', 'sag']

In [31]:
params = dict(penalty=penalty,C=c_values,solver=solver)

In [32]:
#gird search cv
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

cv=StratifiedKFold()

gird = GridSearchCV(estimator=model_1, param_grid=params, scoring='accuracy', cv=cv, n_jobs=-1)

In [33]:
gird

,estimator,LogisticRegression()
,param_grid,"{'C': [0.01, 0.1, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['liblinear', 'saga', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [34]:
gird.fit(X_train, y_train)

c:\Users\karan\Desktop\Sleepyy\.spell\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\karan\Desktop\Sleepyy\.spell\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\karan\Desktop\Sleepyy\.spell\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\karan\Desktop\Sleepyy\.spell\Lib\site-packages\sklearn\linear

,estimator,LogisticRegression()
,param_grid,"{'C': [0.01, 0.1, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['liblinear', 'saga', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l1'


In [35]:
gird.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [36]:
gird.best_score_

np.float64(0.9262499999999999)

In [38]:
y_pred = gird.predict(X_test)

In [39]:
score = accuracy_score(y_test, y_pred)
print("Accuracy:", score)   
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)   


Accuracy: 0.94
Confusion Matrix:
 [[98  3]
 [ 9 90]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.97      0.94       101
           1       0.97      0.91      0.94        99

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.94       200
weighted avg       0.94      0.94      0.94       200



array([0, 1])

In [41]:
#randomized search cv
from sklearn.model_selection import RandomizedSearchCV
random_cv = RandomizedSearchCV(estimator=model_1,param_distributions=params,scoring='accuracy',cv=5,n_jobs=-1)

In [42]:
random_cv.fit(X_train, y_train)

c:\Users\karan\Desktop\Sleepyy\.spell\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\karan\Desktop\Sleepyy\.spell\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\karan\Desktop\Sleepyy\.spell\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\karan\Desktop\Sleepyy\.spell\Lib\site-packages\sklearn\linear_mo

,estimator,LogisticRegression()
,param_distributions,"{'C': [0.01, 0.1, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['liblinear', 'saga', ...]}"
,n_iter,10
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [44]:
random_cv.best_score_

np.float64(0.9112500000000001)

In [45]:
random_cv.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 100}

In [46]:
y_pred = random_cv.predict(X_test)

In [47]:
score = accuracy_score(y_test, y_pred)
print("Accuracy:", score)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)


Accuracy: 0.93
Confusion Matrix:
 [[96  5]
 [ 9 90]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.95      0.93       101
           1       0.95      0.91      0.93        99

    accuracy                           0.93       200
   macro avg       0.93      0.93      0.93       200
weighted avg       0.93      0.93      0.93       200



In [49]:
X, y = make_classification(n_samples=1000,n_informative=3, n_features=10,n_classes=3,random_state=15)

In [50]:
print(X.shape)

(1000, 10)


In [54]:
print(y)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

[2 0 0 0 1 0 1 0 2 1 0 1 0 1 0 0 0 1 1 0 1 2 2 1 1 0 2 0 2 1 2 1 2 2 0 1 2
 1 1 2 1 1 2 2 0 2 1 0 2 0 0 1 0 1 1 0 2 2 0 1 1 2 0 0 1 0 0 1 2 2 0 1 2 2
 1 2 0 2 0 0 1 0 2 0 2 0 0 2 1 2 0 0 2 0 1 0 2 0 2 1 0 0 2 2 0 2 2 0 1 0 1
 0 1 2 1 1 1 2 0 2 0 2 1 1 0 0 1 1 2 2 1 2 0 1 2 2 0 2 2 0 0 1 0 2 0 1 2 0
 2 1 1 0 2 1 0 2 2 2 2 2 1 0 1 0 0 1 1 1 0 1 1 0 1 0 0 0 2 2 1 2 2 2 2 0 1
 0 1 0 2 2 2 1 1 0 0 0 2 0 0 0 1 0 2 1 0 2 2 1 1 1 1 2 0 1 2 2 1 1 0 2 2 1
 0 2 2 1 0 1 2 0 2 1 0 0 1 2 0 0 0 0 2 1 1 0 0 1 0 1 0 1 0 2 2 1 0 1 1 2 2
 2 2 0 1 0 0 2 2 1 2 0 0 1 1 2 2 1 0 0 1 0 1 2 1 0 1 0 2 0 1 0 0 2 2 1 0 2
 0 1 2 2 2 2 0 0 0 0 1 0 1 2 0 0 2 0 0 2 1 0 2 0 0 1 0 0 1 2 1 1 1 1 2 1 1
 1 2 2 1 2 0 1 0 2 2 1 2 0 0 2 1 1 2 1 1 0 2 2 0 2 1 0 0 2 2 1 0 2 0 1 0 2
 2 1 2 2 0 2 0 2 0 2 0 2 2 2 1 2 2 1 1 0 0 1 1 0 1 0 1 1 1 2 1 0 2 2 0 1 0
 1 2 0 1 1 1 0 1 2 0 1 1 2 2 0 2 1 2 0 1 1 2 1 0 2 1 1 2 1 0 2 1 0 0 0 2 1
 0 1 0 2 0 0 1 2 1 1 2 2 1 1 2 2 2 1 0 2 2 2 0 2 0 0 2 1 0 1 1 1 1 2 2 0 0
 1 0 0 1 1 1 1 0 1 2 0 0 

In [55]:
logstic = LogisticRegression(multi_class='ovr')
logstic.fit(X_train, y_train)
y_pred = logstic.predict(X_test)
score = accuracy_score(y_test, y_pred)
print("Accuracy:", score)

Accuracy: 0.79


c:\Users\karan\Desktop\Sleepyy\.spell\Lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [56]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[51  6  6]
 [ 2 50 17]
 [ 6  5 57]]
